name: Deploy To DigitalCoean

# Trigger the workflow on push and
# pull request events on the production branch
on:
  push:
    branches:
      - ola-dev
  pull_request:
    branches:
      - ola-dev

# Authenticate to the the server via ssh
# and run our deployment script
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to server
        uses: appleboy/ssh-action@main
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSHKEY }}
          script: "cd /var/www/githubactiontesting && ./.scripts/deploy.sh"
